// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_appsync_graphqlEndpoint": process.env.REACT_APP_APPSYNC_URL,
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    // "aws_cognito_identity_pool_id": 
    "aws_user_pools_id": "us-east-1_Zy97gNB6Y",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_web_client_id": "6oms760j5rfral52l8pmd2s7ek",
    "aws_appsync_apiKey": process.env.REACT_APP_APPSYNC_API_KEY,
    
    
    // "aws_appsync_authenticationType": "API_KEY",
};

export default awsmobile;