export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';

export const REQUEST_CAUSES_PENDING = 'REQUEST_CAUSES_PENDING';
export const REQUEST_CAUSES_SUCCESS = 'REQUEST_CAUSES_SUCCESS';
export const REQUEST_CAUSES_FAILED = 'REQUEST_CAUSES_FAILED';