export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';

export const REQUEST_CAUSES_PENDING = 'REQUEST_CAUSES_PENDING';
export const REQUEST_CAUSES_SUCCESS = 'REQUEST_CAUSES_SUCCESS';
export const REQUEST_CAUSES_FAILED = 'REQUEST_CAUSES_FAILED';
export const REQUEST_CAUSE_PENDING = 'REQUEST_CAUSE_PENDING';
export const REQUEST_CAUSE_SUCCESS = 'REQUEST_CAUSE_SUCCESS';
export const REQUEST_CAUSE_FAILED = 'REQUEST_CAUSE_FAILED';