export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';

export const REQUEST_CAUSES_PENDING = 'REQUEST_CAUSES_PENDING';
export const REQUEST_CAUSES_SUCCESS = 'REQUEST_CAUSES_SUCCESS';
export const REQUEST_CAUSES_FAILED  = 'REQUEST_CAUSES_FAILED';
export const REQUEST_CAUSE_PENDING  = 'REQUEST_CAUSE_PENDING';
export const REQUEST_CAUSE_SUCCESS  = 'REQUEST_CAUSE_SUCCESS';
export const REQUEST_CAUSE_FAILED   = 'REQUEST_CAUSE_FAILED';
export const ADD_EVENT_PENDING      = 'ADD_EVENT_PENDING';
export const ADD_EVENT_SUCCESS      = 'ADD_EVENT_SUCCESS';
export const ADD_EVENT_FAILED       = 'ADD_EVENT_FAILED';
export const REQUEST_EVENT_PENDING  = 'REQUEST_EVENT_PENDING';
export const REQUEST_EVENT_SUCCESS  = 'REQUEST_EVENT_SUCCESS';
export const REQUEST_EVENT_FAILED   = 'REQUEST_EVENT_FAILED';
export const REQUEST_EVENT_FOR_EDIT_SUCCESS  = 'REQUEST_EVENT_FOR_EDIT_SUCCESS';
export const REQUEST_EVENT_FOR_EDIT_FAILED   = 'REQUEST_EVENT_FOR_EDIT_FAILED';
export const REQUEST_EVENT_FOR_EDIT_PENDING  = 'REQUEST_EVENT_FOR_EDIT_PENDING';
export const REQUEST_DATA_FOR_RSVP_SUCCESS  = 'REQUEST_DATA_FOR_RSVP_SUCCESS';
export const REQUEST_DATA_FOR_RSVP_FAILED   = 'REQUEST_DATA_FOR_RSVP_FAILED';
export const REQUEST_DATA_FOR_RSVP_PENDING  = 'REQUEST_DATA_FOR_RSVP_PENDING';


